using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LevelList : MonoBehaviour
{
    public string[] levelNames = {
        "Humble Beginnings",
        "That's the Key",
        "Circular Thinking",
        "The Big Squeeze",
        "Meet Running Roger",
        "One Way Street",
        "Thought Spiral",
        "Meet Bobbing Barry",
        "A-Maze-Ment",
        "Block Party",
        "Commitment Issues",
        "Self Reflection",
        "One Step Forward",
        "Closing in",
        "Roll of the Dice",
        "Illusion of Choice",
        "No Turning Back",
        "Two Wrongs",
        "A Game Of Two Halves",
        "Two Steps Back",
        "Uneven Ground",
        "Going In Circles",
        "Looping Statement",
        "Meet Yielding Yazmin",
        "Roadblock",
        "Snake In The Headlights",
        "A Little Of Everything",
        "Playing Chicken",
        "Abrasive Affection",
        "Go For A Whirl",
        "Shifting Safety",
        "Hot Timing",
        "Infernal Labyrinth",
        "The Sea Of Fire",
        "Pick Your Moment",
        "Meet Gyroscopic Gerry",
        "The Centrifuge",
        "Key, Cross, Goal",
        "A Square Peg",
        "Seventh Circle",
        "Sight for Saw eyes",
        "Rusty Infiltration",
        "Show Me A Sine",
        "Shocking Surprise",
        "Chase Sequence",
        "Machine Input",
        "Conveyance",
        "Processing Plant",
        "Distribution Centre",
        "The Refuse Chute",
        "The Hidden Base",
        "Dancing Betwixt Bullets",
        "The Haywire Cannon",
        "Corridor Cascade",
        "Bullet Barrage",
        "Periodical Punishment",
        "Tight Spaces",
        "Meaningful Motions",
        "Procedural Difficulty",
        "The Cave Escape",
        "Meet Pursuant Peter",
        "The Slowest Door",
        "Action And Reaction",
        "Multipath Maze",
        "Thread The Needle",
        "Combination Lock",
        "Unending Pursuit",
        "Trackside Hazards",
        "Labyrinthine Languish",
        "The Ineffective Chaser",
        "Carried On Clouds",
        "Dodging Detritus",
        "Tense Travel",
        "Temperamental Flooring",
        "Synchronised Shockers",
        "Viney Villains",
        "Look Both Ways",
        "Cyclical Cloud Surfing",
        "The Autoscroller",
        "Congestion In The Clouds",
        "Moon Base Alpha",
        "Clear The Chasms",
        "Gauntlet For The Gold",
        "Whirl of a time",
        "Meet Slinging Simon",
        "Frontal Assault",
        "That Sinking Feeling",
        "Going For A Spin",
        "Beaming With Joy",
        "The Desperate Retreat",
        "A Study On: Toyblock Forest",
        "A Study On: Icicle Palace",
        "A Study On: Shifting Desert",
        "A Study On: Sweltering Volcano",
        "A Study On: Automated Factory",
        "A Study On: Crystal Caverns",
        "A Study On: Jade Ruins",
        "A Study On: Clouded Sky",
        "A Study On: Barren Moon",
        "The Office Of The Boss",
    };
}
